### PR TITLE
add latlong lookup and begin emergency info lookup functions, switch to Folio

### PR DESCRIPTION
**Pull request by razzlestorm**
# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by tallywiesenberg — COMMENTED** [review]
Have you tested lat_long_finder yet? Looks robust though. Great work!

**Comment by razzlestorm** [comment]
Going to write a test for this!

**Comment by razzlestorm** [comment]
Test written and passed successfully! @tallywiesenberg Are you able to review and merge this when you get a chance?

**Review by lechemrc — APPROVED** [review]
This all looks excellent. Nice work on the testing within. I especially liked the latlong finder.

**Comment by tallywiesenberg** [comment]
This looks excellent! One thing we should look for in the future is how to access a user's home city from the DB for centering the map on that city's coords.

**Pull request merged**
